### PR TITLE
[308] Make CDI and MP Config imports optional

### LINKED ISSUE #308: OSGi: does RestClientBuilder (non-CDI) require MP Config at runtime?
Hi!

I'm trying to integrate a 3rd-party component that uses `RestClientBuilder` [programmatically](https://github.com/ma1uta/jmsdk/blob/master/client-impl/src/main/java/io/github/ma1uta/matrix/client/MatrixClient.java#L146), as far as I can tell. Reading the [spec](https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#mpconfig), I understand that "it is **possible** to use MicroProfile Config", **if** one uses CDI. That should imply that non-CDI implementations shouldn't require MP Config at runtime. However, the OSGi resolver returns this:
```
Unable to resolve org.eclipse.microprofile.rest.client/2.0.0: missing requirement [org.eclipse.microprofile.rest.client/2.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.eclipse.microprofile.config)(version>=2.0.0)(!(version>=3.0.0)))"
[caused by: Unable to resolve org.eclipse.microprofile.config/2.0.0: missing requirement [org.eclipse.microprofile.config/2.0.0] osgi.serviceloader; osgi.serviceloader=org.eclipse.microprofile.config.spi.ConfigProviderResolver; filter:="(osgi.serviceloader=org.eclipse.microprofile.config.spi.ConfigProviderResolver)"; effective:=active]
```
What am I missing (literally)? Do I have to provide a service implementing the `ConfigProviderResolver` interface, even if `RestClientBuilder` is used only programmatically?

Thanks

### PR DESCRIPTION
**Pull request by andymc12**
Fixes #308

### CODE REVIEW

**Comment by brevilo** [comment]
Just curious, is there anything I can do to facilitate the merge?

**Comment by andymc12** [comment]
Hi @brevilo - sorry for the delay - the weather was pretty nice here yesterday, so I took the day off.  :) I wanted to make sure any other committer on the project had a chance to review.  I'll go ahead and merge now.  Thanks!

**Comment by brevilo** [comment]
No worries :) What's the release schedule to get this show-stopper out of the way for production?

**Comment by brevilo** [comment]
Ok, understood. That should certainly be enough if the RC also shows up in maven central, for instance.

Nice one!

**Pull request merged**
