### PR TITLE
[244] Use provided scope for all API dependencies

### PR DESCRIPTION
**Pull request by andymc12**
Using provided scopes as to not repackage dependencies.  

Organizing dependency versions in parent POM.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
This can't be merged until after a possible minor release for MP 3.3 correct?

**Comment by andymc12** [comment]
Yes, that's correct.  I'll hold off from merging this.  I think I may end up creating a new branch (1.4.x) - and I'll need to revert the Jakarta dependencies change in that one.  Once there is a separate branch from 1.4.x, then we should be good to merge this into master.  Thanks, Ken!

**Comment by kenfinnigan** [comment]
If there's lots of things in master we wouldn't release for 1.4, maybe create 1.4 branch from 1.3 latest tag and just bring across the needed commits.

Saves reverting master

**Comment by andymc12** [comment]
> If there's lots of things in master we wouldn't release for 1.4, maybe create 1.4 branch from 1.3 latest tag and just bring across the needed commits.

Good call - that's what I ended up doing.  This Pull Request should be good to go into master - and should not be backported.  The other active pull requests should go into master, but should also be backported.

**Comment by andymc12** [comment]
Resolves issue #244.

**Pull request merged**
