### PR TITLE
Update dependency version

### PR DESCRIPTION
**Pull request by automatictester**

### CODE REVIEW

**Comment by automatictester** [comment]
Signed-off-by: Ireneusz Pastusiak ireneusz.pastusiak@gmail.com

**Comment by kenfinnigan** [comment]
@automatictester Have you signed the Eclipse Contributor Agreement, as it appears the IP validation is failing because you haven't? Unfortunately, without that we wouldn't be able to accept the PR

**Comment by automatictester** [comment]
Hi @kenfinnigan please see my comment above. Yes I have signed it already.

**Comment by kenfinnigan** [comment]
@automatictester I see you've signed the commit, but according to https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=5c31fdb1c3f94 you don't have an Eclipse Contributor Agreement. Are you an Eclipse Committer?

**Comment by automatictester** [comment]
I have signed it, but only after the initial IP check on this PR failed. I have a green checkbox next to Eclipse Contributor Agreement under https://accounts.eclipse.org/user.

**Comment by kenfinnigan** [comment]
Ah ok, I'm not sure how, or if, we can retrigger the validation check.

It's a bit annoying, but could you close and open a new PR?

**Pull request closed without merging**
