### PR TITLE
Fixes #222

### LINKED ISSUE #222: InvokeWithJsonPProviderTest doesn't use @RestClient
I presume it's an omission that https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/InvokeWithJsonPProviderTest.java#L65 doesn't have `@RestClient` on the injection point for the CDI bean?

### PR DESCRIPTION
**Pull request by kenfinnigan**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Thanks @andymc12!

What's involved in triggering a 1.3.x release? Not sure I need one right now, still need to verify some things first, but wanted to ask

**Comment by andymc12** [comment]
Hi @kenfinnigan - It wouldn't be a bad idea to publish a new 1.3.x release - I think we have added 2-3 updates to the TCK and Javadoc.

Basically, we would need to follow this procedure:
https://wiki.eclipse.org/MicroProfile/SpecRelease/Release

The new release/tag should be `1.3.4`, and the next release should be `1.3.5-SNAPSHOT`.

If you want me to kick it off, just let me know.  Thanks!

**Comment by kenfinnigan** [comment]
@andymc12 are you able to kick off a release of 1.3.4?

If not, I can make an attempt at a first time!

**Comment by andymc12** [comment]
@kenfinnigan Sure - I'll kick it off as soon as my meeting is over.  If all goes well, it should be available in a few hours - though sometimes it takes a little longer (like 24-48 hours) to get mirrored on maven central.

**Comment by kenfinnigan** [comment]
Awesome, thanks!

**Pull request merged**
