### PR TITLE
[#267] Allow to use defaults for some config settings

### PR DESCRIPTION
**Pull request by pilhuhn**
Add the possibility to have default for some of the configuration options, so that those settings do not need to repeated for each service client.

Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>

### CODE REVIEW

**Comment by sebthom** [comment]
@pilhuhn could you please also include keyStore and trustStore related properties

**Comment by andymc12** [comment]
Hi @pilhuhn - I'm starting to pick back up into the new features for MP Rest Client (sorry for the long delay).  Are you still available to work on this item?  I think the main things that are missing are TCK tests (let me know if I can help with those) and @sebthom 's suggestion to include keyStore and trustStore properties.  Thanks!

**Comment by sebthom** [comment]
@andymc12 any updates? e.g. has this maybe already been solved via another PR?

**Comment by Emily-Jiang** [comment]
This PR is nearly 4 years old and it seems that the required action was not taken. Close this for now. Please open a separate PR to address the concerns.

**Pull request closed without merging**
