### PR TITLE
Enable SPI/ServiceLoader under OSGi

### PR DESCRIPTION
**Pull request by brevilo**
* Using OSGi's [Service Loader Mediator](https://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html) (i.e. Apache Aries [SPI Fly](https://aries.apache.org/documentation/modules/spi-fly.html))
* Made all requirements optional (minimally invasive change)

Based on the following discussion: https://github.com/eclipse/microprofile-rest-client/issues/308#issuecomment-813638983

Cheers

### CODE REVIEW

**Comment by brevilo** [comment]
@andymc12, feel free to merge my changes into a PR of your own.

**Review by andymc12 — APPROVED** [review]
This lgtm - I'll plan to leave the PR open over the long (US) weekend in case anybody else would like to review it.  Thanks @brevilo!

**Comment by brevilo** [comment]
Hi @andymc12, do you think this one is ready to merge now...? ;)

**Comment by andymc12** [comment]
Sorry for the delay on this @brevilo  - thanks again for the PR!

**Comment by brevilo** [comment]
Thanks! Anytime!

**Comment by brevilo** [comment]
BTW, how about another RC release? 😏

**Comment by andymc12** [comment]
@brevilo 
> BTW, how about another (RC) release? 😏 Would love to get rid of another fork...

Just released https://github.com/eclipse/microprofile-rest-client/releases/tag/2.0.1-RC2

**Comment by brevilo** [comment]
Awesome! One down, [two](https://github.com/eclipse/microprofile-rest-client/issues/308#issuecomment-850332634) remaining (at CXF)...

**Comment by brevilo** [comment]
> @brevilo
> 
> > BTW, how about another (RC) release? 😏 Would love to get rid of another fork...
> 
> Just released https://github.com/eclipse/microprofile-rest-client/releases/tag/2.0.1-RC2

Hm, @andymc12 can you please check that again? I don't tink it's part of that release candidate: https://github.com/eclipse/microprofile-rest-client/compare/2.0.1-RC1...2.0.1-RC2 (or any tag for that matter, just in `master` so far).

Thanks

**Comment by andymc12** [comment]
@brevilo good catch - I must not have backported the changes to `2.0.X-service` before publishing RC2.  I have published RC3 now which show your latest change and mine:
https://github.com/eclipse/microprofile-rest-client/compare/2.0.1-RC2...2.0.1-RC3

Here is the release page:
https://github.com/eclipse/microprofile-rest-client/releases/tag/2.0.1-RC3

Thanks!

**Comment by brevilo** [comment]
You're welcome 👍 Thanks for the swift action - works like a charm!

**Pull request merged**
