### PR TITLE
[334] - add String overloaded RestClientBuilder.baseUri() method

### PR DESCRIPTION
**Pull request by WhiteCat22**
Added a `String` overloaded `RestClientBuilder.baseUri()` method to the API.

### CODE REVIEW

**Review by jamezp — APPROVED** [review]

**Review by jim-krueger — APPROVED** [review]

**Review by Emily-Jiang — COMMENTED** [review]
Can you also add a TCK for this API change? Can you also check to see whether you can make a spec change as well?

**Comment by jim-krueger** [comment]
@Emily-Jiang Adam is already considering TCK for this and talking with James and me about it in slack.   

It will probably be best going forward to not consider that a PR is ready to merge until we directly request that you merge it.
Thanks

**Comment by WhiteCat22** [comment]
I've finally found time to talk to both Jim and James and the consensus is that a TCK test isn't really appropriate, since the implementation is in the API. A TCK test would just be testing the JDK's implementation on `URI.create()` rather than the MpRestClient implementation.

Additionally, I don't think a spec change is appropriate either since we don't go into specific details for other API methods. We aren't adding new functionality that needs to be documented. We're just adding additional options for existing functionality to the API which is clearly detailed by the javadoc.

**Comment by jamezp** [comment]
Agreed, I don't see a need for a TCK test for a single method.

**Comment by jim-krueger** [comment]
@Emily-Jiang This is ready to be merged.

**Comment by WhiteCat22** [comment]
resolves #334"

**Pull request merged**
