### PR TITLE
[Issue 203] Fix race condition in removeContext test

### PR DESCRIPTION
**Pull request by andymc12**
This change recycles the thread used for the asynchronous work (after the rest client work is done) and verifies that the thread locals set by the async rest client flow have been cleared.

This should go into `1.3.X-service` and `master`.

This should resolve issue #203.

Signed-off-by: Andy McCright <j.andrew.mccright@gmail.com>

### CODE REVIEW

**Comment by andymc12** [comment]
@stuartwdouglas  @reta - could you test to verify that this fixes the issue(s) you are seeing?  I've run this several times locally (with Liberty that uses CXF) and it passes, but I never saw it fail before these changes.

**Comment by kenfinnigan** [comment]
@cescoffier @asoldano @ronsigal any comments?

**Comment by reta** [comment]
@andymc12 thanks a lot for the fix, I will give it a try shortly

**Comment by asoldano** [comment]
@kenfinnigan , I haven't reproduced the issue, but the changes look ok.

**Comment by reta** [comment]
@andymc12 I was playing with the TCK today (against CXF MP client). While the current implementation of the `AsyncMethodTest::testAsyncInvocationInterceptorProvider` was failing often, after applying the patch (this PR) I have not seen any failures anymore. Thanks again!

**Pull request merged**
